#!/usr/bin/env bash
set -o nounset
set -o errexit
set -o pipefail

TUN_INTERFACE_COUNT=5
TUN_SUBNET_PREFIX="10.0"
TUN_SUBNET="${TUN_SUBNET_PREFIX}.0.0/8"

if [ $# -ne 1 ]; then
    echo "Usage: $0 <up|down>" >&2
    exit 1
fi

CURRENT_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
ROOT_DIR="$(realpath "${CURRENT_DIR}/..")"
CONFIG_DIR="${ROOT_DIR}/dev-config"

CONFIGURED_INTERNET_INTERFACE_NAME_FILE="${CONFIG_DIR}/internet-interface-name"

function get_default_interface() {
    local internet_route
    internet_route="$(ip route show default | head --lines 1)"

    if [ -z "${internet_route}" ]; then
        echo "Error: No internet route found" >&2
        exit 2
    fi

    echo "${internet_route}" | awk '{print $5}'
}

function set_internet_interface_name() {
    local internet_interface="$1"

    mkdir --parents "$(dirname "${CONFIGURED_INTERNET_INTERFACE_NAME_FILE}")"

    echo "${internet_interface}" > "${CONFIGURED_INTERNET_INTERFACE_NAME_FILE}"
}

function unset_internet_interface_name() {
    rm "${CONFIGURED_INTERNET_INTERFACE_NAME_FILE}"
}

function is_internet_interface_set() {
    [ -f "${CONFIGURED_INTERNET_INTERFACE_NAME_FILE}" ]
}

function get_internet_interface_name() {
    cat "${CONFIGURED_INTERNET_INTERFACE_NAME_FILE}"
}

function is_traffic_from_tun_interfaces_masqueraded() {
    local internet_interface="$1"

    if ! sudo iptables --table nat --check POSTROUTING --out-interface "${internet_interface}" --source "${TUN_SUBNET}" --destination 0.0.0.0/0 --jump MASQUERADE 2>>/dev/null; then
        return 1
    fi

    return 0
}

function masquerade_traffic_from_tun_interfaces() {
    local internet_interface="$1"

    sudo iptables --table nat \
        --append POSTROUTING \
        --jump MASQUERADE \
        --out-interface "${internet_interface}" \
        --source "${TUN_SUBNET}" \
        --destination 0.0.0.0/0
}

function drop_masquerading_from_tun_interfaces() {
    local internet_interface="$1"

    sudo iptables --table nat \
        --delete POSTROUTING \
        --jump MASQUERADE \
        --out-interface "${internet_interface}" \
        --source "${TUN_SUBNET}" \
        --destination 0.0.0.0/0
}

function create_tun_interface() {
    local interface_name="$1"
    local interface_subnet="$2"

    if ip link show "${interface_name}" &> /dev/null; then
        sudo ip link set down dev "${interface_name}"
        sudo ip addr flush dev "${interface_name}"
    else
        sudo ip tuntap add dev "${interface_name}" mode tun user "${USER}"
    fi

    sudo ip addr add "${interface_subnet}" dev "${interface_name}"
    sudo ip link set up dev "${interface_name}"

    local interface_address
    interface_address="$(echo "${interface_subnet}" | cut -d'/' -f1)"
    sudo ip route add "${interface_address}/32" dev "${interface_name}"

    echo "Configured ${interface_name} with ${interface_subnet}"
}

function delete_tun_interface() {
    local interface_name="$1"

    if ip link show "${interface_name}" &> /dev/null; then
        echo "Deleting ${interface_name}..."
        sudo ip link set down dev "${interface_name}"
        sudo ip tuntap del dev "${interface_name}" mode tun
    else
        echo "${interface_name} does not exist, skipping deletion"
    fi
}

function remove_route_if_exists() {
    local interface_subnet="$1"
    if ip route show exact "${interface_subnet}" &> /dev/null; then
        echo "Removing route for ${interface_subnet}..."
        # TODO: Do we need the fallback to echo?
        sudo ip route del "${interface_subnet}" || echo "Warning: Failed to remove route for ${interface_subnet}"
    fi
}

function add_route_if_not_exists() {
    local interface_subnet="$1"
    local tun="$2"
    if ip route show exact "${interface_subnet}" &> /dev/null; then
        echo "Route for ${interface_subnet} already exists, skipping..."
    else
        echo "Adding route for ${interface_subnet}..."
        if ! sudo ip route add "${interface_subnet}" dev "${tun}"; then
            # TODO: Do we need the fallback to echo?
            echo "Warning: Failed to add route for ${interface_subnet}"
        fi
    fi
}

function remove_routing_rules() {
    local internet_interface="$1"

    for index in $(seq 0 $((TUN_INTERFACE_COUNT - 1))); do
        local interface_subnet="${TUN_SUBNET_PREFIX}.$(( 100 + index )).0/24"
        local tun="tun${index}"

        echo "Removing routing for ${tun}..."

        sudo iptables -D FORWARD -i "${internet_interface}" -o "${tun}" -j ACCEPT 2>/dev/null || true

        sudo ip route del "${interface_subnet}" dev "${tun}" 2>/dev/null || true
    done
}

function add_routing_rules() {
    local internet_interface="$1"

    for index in $(seq 0 $((TUN_INTERFACE_COUNT - 1))); do
        local interface_subnet="${TUN_SUBNET_PREFIX}.$(( 100 + index )).0/24"
        local tun="tun${index}"

        echo "Setting up routing for ${tun}..."

        sudo iptables -A FORWARD -i "${internet_interface}" -o "${tun}" -j ACCEPT

        # Add a route for the TUN interface_subnet (if not already added by create_tun_interface)
        sudo ip route add "${interface_subnet}" dev "${tun}" 2>/dev/null || true
    done
}

function set_up() {
    local internet_interface
    internet_interface="$(get_default_interface)"

    if ! grep --fixed-strings --quiet "1" "/proc/sys/net/ipv4/conf/${internet_interface}/forwarding"; then
        echo "Error: IPv4 forwarding is not enabled on ${internet_interface}" >&2
        exit 3
    fi

    for index in $(seq 0 $((TUN_INTERFACE_COUNT - 1))); do
        create_tun_interface "tun${index}" "${TUN_SUBNET_PREFIX}.$(( 100 + index )).1/24"
    done

    # Configure routing
    set_internet_interface_name "${internet_interface}"
    if ! is_traffic_from_tun_interfaces_masqueraded "${internet_interface}"; then
        masquerade_traffic_from_tun_interfaces "${internet_interface}"
        echo "Set up NAT to masquerade traffic from TUN interfaces to ${internet_interface}"
    else
        echo "NAT masquerading already set up for TUN interfaces to ${internet_interface}"
    fi

    remove_routing_rules "${internet_interface}"
    add_routing_rules "${internet_interface}"
    echo "Updated routing rules for TUN interfaces"

    echo "Current routing table:"
    ip route show
    echo "Current iptables FORWARD rules:"
    sudo iptables -L FORWARD
    echo "Current iptables NAT rules:"
    sudo iptables -t nat -L POSTROUTING
}

function tear_down() {
    if is_internet_interface_set; then
        local internet_interface
        internet_interface="$(get_internet_interface_name)"

        remove_routing_rules "${internet_interface}"
        echo "Removed routing rules for TUN interfaces"

        if is_traffic_from_tun_interfaces_masqueraded "${internet_interface}"; then
            drop_masquerading_from_tun_interfaces "${internet_interface}"
            echo "Removed NAT masquerading for traffic from TUN interfaces to ${internet_interface}"
        fi

        unset_internet_interface_name
    fi

    for index in $(seq 0 $((TUN_INTERFACE_COUNT - 1))); do
        delete_tun_interface "tun${index}"
    done

    echo "Current routing table:"
    ip route show
    echo "Current iptables FORWARD rules:"
    sudo iptables -L FORWARD
    echo "Current iptables NAT rules:"
    sudo iptables -t nat -L POSTROUTING
}

case "$1" in
    up)
        set_up
        ;;
    down)
        tear_down
        ;;
    *)
        exit 1
        ;;
esac
